export const OrderList = [
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Pending",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Delivered",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Picked",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Pending",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Pending",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Processing",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Shipped",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Confirmed",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Processing",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Pending",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Confirmed",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Pending",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Cancelled",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Processing",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Pending",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Pending",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Picked",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Pending",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Pending",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Confirmed",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Picked",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5284",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Pending",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5285",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Confirmed",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5286",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Pending",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5287",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Confirmed",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5288",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Pending",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5289",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Processing",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5280",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Confirmed",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5291",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Picked",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5292",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Pending",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5293",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Processing",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5293",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Cancelled",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5293",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Shipped",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5293",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Cancelled",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5293",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Picked",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5293",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Processing",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5293",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Cancelled",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5293",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Processing",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5293",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Delivered",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5293",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Delivered",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5293",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Processing",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5293",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Shipped",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5293",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Processing",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5293",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Delivered",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5293",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Processing",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
  {
    orderId: "#5293",
    timestamp: new Date().toLocaleDateString("en-us"),
    customerName: "Joseph wheeler",
    totalAmount: 20000,
    status: "Delivered",
    profit: 1200,
    products: [
      {
        productId: "#6876",
        productName: "Bama",
        price: 3000,
        originalPrice: 2000,
        sellingPrice: 2700,
        quantity: 1,
        discount: 0,
        total: 2700,
      },
      {
        productId: "#6876",
        productName: "Shoe",
        price: 20000,
        originalPrice: 16000,
        sellingPrice: 17300,
        quantity: 1,
        discount: 10,
        total: 17300,
      },
    ],
  },
];
